# Generated by Django 4.2.8 on 2023-12-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_detail',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
