# Generated by Django 4.2.8 on 2023-12-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_public_votting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='public_votting',
        ),
    ]
